"""empty message

Revision ID: 57885ba3016
Revises: 3f8c3df8463
Create Date: 2015-03-13 10:28:28.820812

"""

# revision identifiers, used by Alembic.
revision = '57885ba3016'
down_revision = '3f8c3df8463'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('adjustment', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'adjustment')
    ### end Alembic commands ###
